name: Export Pluto notebooks
on:
    push:
        branches:
            - main
    workflow_dispatch:

concurrency:
    group: pluto-export
    cancel-in-progress: true

permissions:
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Install lualatex
              run: sudo apt-get update && sudo apt-get install -y texlive-full
              
            - name: Checkout this repository
              uses: actions/checkout@v4

            - name: Install Julia
              uses: julia-actions/setup-julia@v2
              with:
                  version: '1'

            - name: Cache Julia artifacts
              uses: julia-actions/cache@v2
              with:
                cache-registries: "true"

            - name: Set up notebook state cache
              uses: actions/cache@v4
              with:
                  path: pluto_state_cache
                  key: ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml', '.github/workflows/*' ) }}-${{ hashFiles('**/*jl') }}
                  restore-keys: |
                      ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml', '.github/workflows/*' ) }}

            - name: Ignore notebook state cache in export
              run: echo 'pluto_state_cache' >> .gitignore

            - name: Run & export Pluto notebooks
              run: |
                julia -e 'using Pkg
                  Pkg.activate(mktempdir())
                  Pkg.add([
                    Pkg.PackageSpec(name="PlutoSliderServer", version="1"),
                  ])

                  import PlutoSliderServer

                  PlutoSliderServer.github_action(".";
                    Export_cache_dir="pluto_state_cache",
                    Export_baked_notebookfile=false,
                    Export_baked_state=false,
                  )'

            - name: Deploy to gh-pages
              uses: JamesIves/github-pages-deploy-action@releases/v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: gh-pages
                  folder: .
                  single-commit: true
                  clean-exclude: |
                      _config.yml
                      index.md
                      index.html
