name: Export Pluto notebooks
on:
    push:
        branches:
            - main
    workflow_dispatch:

concurrency:
    group: pages
    cancel-in-progress: false

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install lualatex
              run: sudo apt-get update && sudo apt-get install -y texlive-full

            - name: Install GSL
              run: sudo apt-get install -y libgsl-dev

            - name: Checkout this repository
              uses: actions/checkout@v7

            - name: Install Julia
              uses: julia-actions/setup-julia@v3
              with:
                  version: '1'

            - name: Cache Julia artifacts
              uses: julia-actions/cache@v3
              with:
                cache-registries: "true"

            - name: Set up notebook state cache
              uses: actions/cache@v6
              with:
                  path: pluto_state_cache
                  key: ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml', '.github/workflows/*' ) }}-${{ hashFiles('**/*jl') }}
                  restore-keys: |
                      ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml', '.github/workflows/*' ) }}

            - name: Run & export Pluto notebooks
              run: |
                julia -e 'using Pkg
                  Pkg.activate(mktempdir())
                  Pkg.add([
                    Pkg.PackageSpec(name="PlutoSliderServer", version="1"),
                  ])

                  import PlutoSliderServer

                  PlutoSliderServer.github_action(".";
                    Export_cache_dir="pluto_state_cache",
                    Export_baked_notebookfile=false,
                    Export_baked_state=false,
                  )'

            - name: Remove notebook state cache from artifact
              run: rm -rf pluto_state_cache

            - name: Upload Pages artifact
              uses: actions/upload-pages-artifact@v5
              with:
                  path: .

    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v5
